export const CHANGE_ATTRIBUTE = 'CHANGE_ATTRIBUTE';
export const ADD_LIST = 'ADD_LIST';
export const ADD_CARD = 'ADD_CARD';
export const DRAG_OCCURRED = 'DRAG_OCCURRED';
export const REQUEST_BOARDS_PENDING = 'REQUEST_BOARDS_PENDING';
export const REQUEST_BOARDS_SUCCESS = 'REQUEST_BOARDS_SUCCESS';
export const REQUEST_BOARDS_FAILED = 'REQUEST_BOARDS_FAILED';
export const EDIT_BOARD_TITLE = 'EDIT_BOARD_TITLE';
